# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-07da4914-78f7-4ebd-b9d7-903c650c58d0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-07da4914-78f7-4ebd-b9d7-903c650c58d0".device = "/dev/disk/by-uuid/07da4914-78f7-4ebd-b9d7-903c650c58d0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A184-CE6F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f34ed86f-36b7-4aa4-b36f-342edb53fe4c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
